In [1]:
import os
import tempfile

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc

/usr/local/lib/python3.12/site-packages/leidenalg/VertexPartition.py:388: SyntaxWarning: invalid escape sequence '\m'
  """ Implements modularity. This quality function is well-defined only for positive edge weights.
/usr/local/lib/python3.12/site-packages/leidenalg/VertexPartition.py:761: SyntaxWarning: invalid escape sequence '\m'
  """ Implements Reichardt and Bornholdt's Potts model with a configuration null model.
/usr/local/lib/python3.12/site-packages/leidenalg/Optimiser.py:7: SyntaxWarning: invalid escape sequence '\g'
  """ Class for doing community detection using the Leiden algorithm.
/usr/local/lib/python3.12/site-packages/leidenalg/Optimiser.py:305: SyntaxWarning: invalid escape sequence '\s'
  """ Optimise the given partitions simultaneously.

In [ ]:
adata_path = '20250811_all_data_integrated_filtered_umap_scANVI_metadata_ct_corrected.annot_corrected.index_dedup.cg.h5ad'  # CC RNA anndata, change name and path as necessarry
adata = sc.read(adata_path)
adata

WARNING: Your filename has more than two extensions: ['.annot_corrected', '.index_dedup', '.cg', '.h5ad'].
Only considering the two last: ['.cg', '.h5ad'].
WARNING: Your filename has more than two extensions: ['.annot_corrected', '.index_dedup', '.cg', '.h5ad'].
Only considering the two last: ['.cg', '.h5ad'].

AnnData object with n_obs × n_vars = 751541 × 39514
    obs: 'sample', 'species', 'gene_count', 'tscp_count', 'mread_count', 'bc1_wind', 'bc2_wind', 'bc3_wind', 'bc1_well', 'bc2_well', 'bc3_well', 'n_counts', 'n_genes', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'pct_counts_hb', 'outlier', 'mt_outlier', 'region', 'vireo_assignment', 'library', 'subclass_scANVI', 'cell_type_scANVI', 'biobank_name', 'sex', 'age_at_collection', 'primary_diagnosis', 'age_at_diagnosis', 'batch', 'new_index', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'doublet_score', 'predicted_doublet', 'experiment', 'prob_max', 'prob_doublet', 'n_vars', 'doublet_logLikRatio', 'leiden_2.5', 'cell_type_majority_old', 'cell_type', 'consensus_cell_type', 'cell_type_broad', 'consensus_cell_type_corrected'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'batch_colors', 'cell_type_broad_colors', 'cell_type_colors', 'cell_type_majority_old_colors', 'cell_type_scANVI_colors', 'consensus_cell_type_colors', 'consensus_cell_type_corrected_colors', 'experiment_colors', 'hvg', 'leiden_2.5', 'leiden_2.5_colors', 'log1p', 'neighbors', 'pca', 'sample_colors', 'umap', 'vireo_assignment_colors'
    obsm: 'X_pca', 'X_scANVI', 'X_scVI', 'X_tsne', 'X_umap'
    varm: 'PCs'
    layers: 'counts', 'log1p_norm'
    obsp: 'connectivities', 'distances'

In [3]:
sc.tl.rank_genes_groups(adata, groupby = 'cell_type_broad', method = 'wilcoxon', layer = 'log1p_norm')

In [4]:
sc.get.rank_genes_groups_df(adata, group="Oligo").head(20)

       names      scores  logfoldchanges  pvals  pvals_adj
0       ST18  517.639343        6.345450    0.0        0.0
1     CTNNA3  489.440887        4.238723    0.0        0.0
2     RNF220  483.746582        4.547774    0.0        0.0
3        MBP  464.298981        3.773790    0.0        0.0
4    PIP4K2A  454.928345        3.388988    0.0        0.0
5    TMEM144  443.175354        4.918151    0.0        0.0
6   C10orf90  417.995789        4.079338    0.0        0.0
7       PLP1  411.608307        5.508069    0.0        0.0
8      DOCK5  408.179962        3.538615    0.0        0.0
9     FRMD4B  404.398590        3.742778    0.0        0.0
10      MOBP  399.110870        5.370952    0.0        0.0
11     ENPP2  397.510010        5.139341    0.0        0.0
12   SLC44A1  393.730682        2.534610    0.0        0.0
13      CLMN  386.329224        3.823587    0.0        0.0
14    DOCK10  373.152802        2.636770    0.0        0.0
15       QKI  367.520752        2.105140    0.0        0.0
16     KCNH8  365.147644        3.898773    0.0        0.0
17    NCKAP5  362.982727        2.666049    0.0        0.0
18     TMTC2  360.138794        2.497310    0.0        0.0
19        TF  350.035828        2.810850    0.0        0.0

In [5]:
ranked_genes = sc.get.rank_genes_groups_df(adata, group="Oligo")
ranked_genes['abs_logfoldchanges'] = ranked_genes['logfoldchanges'].abs()

In [8]:
ranked_genes

,names,scores,logfoldchanges,pvals,pvals_adj,abs_logfoldchanges
0,ST18,517.639343,6.345450,0.0,0.0,6.345450
1,CTNNA3,489.440887,4.238723,0.0,0.0,4.238723
2,RNF220,483.746582,4.547774,0.0,0.0,4.547774
3,MBP,464.298981,3.773790,0.0,0.0,3.773790
4,PIP4K2A,454.928345,3.388988,0.0,0.0,3.388988
...,...,...,...,...,...,...
39509,NALF1,-451.473602,-5.866171,0.0,0.0,5.866171
39510,CELF2,-453.642731,-5.770234,0.0,0.0,5.770234
39511,KCNMA1,-456.038361,-5.763328,0.0,0.0,5.763328
39512,NRXN1,-469.242157,-5.824150,0.0,0.0,5.824150
39513,NRG3,-476.643219,-6.143144,0.0,0.0,6.143144

In [9]:
adata.obs['cell_type_broad'].value_counts()

cell_type_broad
ExN          260309
InN          137135
Astro        122948
Oligo        116404
OPC           59762
Micro-PVM     51148
Endo           3835
Name: count, dtype: int64

In [10]:
cluster_key = 'cell_type_broad'
cluster_of_interest = 'Oligo'#'Oligo'
adata.X = adata.layers['log1p_norm']

adata_cluster = adata[adata.obs[cluster_key] == cluster_of_interest]
mean_expression = adata_cluster.X.mean(axis=0)

if hasattr(mean_expression, "A1"):
    mean_expression = mean_expression.A1  # for sparse matrices
elif isinstance(mean_expression, np.matrix):
    mean_expression = np.asarray(mean_expression).flatten()
else:
    mean_expression = np.ravel(mean_expression)
    
gene_expression = pd.DataFrame({
    'gene': adata.var_names.to_list(),
    'mean_expression': mean_expression
})

In [11]:
gene_expression_sorted = gene_expression.sort_values(by='mean_expression', ascending=False)
gene_expression_sorted

           gene  mean_expression
26980    MALAT1         4.028512
30567     PCDH9         3.146179
9272   IL1RAPL1         2.688106
32337       QKI         2.216876
5063       DLG2         2.167451
...         ...              ...
37137     TRAV6         0.000000
37138     TRAV7         0.000000
37139   TRAV8-1         0.000000
37140   TRAV8-2         0.000000
37143   TRAV8-6         0.000000

[39514 rows x 2 columns]

In [12]:
gene_expression_sorted[:30]

           gene  mean_expression
26980    MALAT1         4.028512
30567     PCDH9         3.146179
9272   IL1RAPL1         2.688106
32337       QKI         2.216876
5063       DLG2         2.167451
4386     CTNNA3         2.144596
30721     PDE4B         2.104969
26962     MAGI2         2.104294
35414      ST18         2.086291
2462      CADM2         2.062403
31696   PPP2R2B         1.974810
34321   SLC24A2         1.861529
32233     PTPRD         1.842212
27188       MBP         1.799358
28854     NCAM2         1.796343
31100   PIP4K2A         1.763551
33098    RNF220         1.741392
34522   SLC44A1         1.729026
7052      FRMD5         1.709368
5389        DST         1.702796
5760      ELMO1         1.667150
31238     PLCL1         1.592347
781        ANK3         1.568812
36812     TMTC2         1.561079
27001    MAN2A1         1.551219
38615    ZBTB20         1.546234
5233       DNM3         1.538003
34149      SIK3         1.533104
6895      FMNL2         1.526425
5562      EDIL3         1.513339

In [13]:
n_genes = len(gene_expression_sorted)
top_n = int(n_genes * 0.1)
top_10_percent = gene_expression_sorted.head(top_n)
bottom_10_percent = gene_expression_sorted.tail(top_n)

In [ ]:
# make sure output dir exists
os.makedirs('expression_info', exist_ok=True)
top_10_percent['gene'].to_csv(f'expression_info/cc_{cluster_of_interest}_top10_expressed_genes.csv', index = False)

In [15]:
bottom_10_percent['gene'].to_csv(f'expression_info/cc_{cluster_of_interest}_bottom10_expressed_genes.csv', index = False)

In [16]:
pip list

Package                   Version
------------------------- --------------
absl-py                   2.1.0
adjustText                1.3.0
aiobotocore               2.17.0
aiohappyeyeballs          2.4.4
aiohttp                   3.11.11
aiohttp-retry             2.9.1
aioitertools              0.12.0
aiosignal                 1.3.2
amqp                      5.3.1
anndata                   0.11.2
anndata2ri                1.3.2
annotated-types           0.7.0
ansicolors                1.1.8
antlr4-python3-runtime    4.9.3
anyio                     4.8.0
appdirs                   1.4.4
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
array_api_compat          1.10.0
arrow                     1.3.0
asttokens                 3.0.0
async-lru                 2.0.4
asyncssh                  2.19.0
atpublic                  5.0
attrs                     24.3.0
babel                     2.16.0
beautifulsoup4            4.12.3
billiard                  4.2.1
biopython                 1.84
biothings-client          0.3.1
bleach                    6.2.0
blitzgsea                 1.3.47
boto3                     1.35.93
botocore                  1.35.93
celery                    5.4.0
certifi                   2024.12.14
cffi                      1.17.1
cfgv                      3.4.0
charset-normalizer        3.4.1
chex                      0.1.88
click                     8.1.8
click-didyoumean          0.3.1
click-plugins             1.1.1
click-repl                0.3.0
cloudpickle               3.1.0
colorama                  0.4.6
comm                      0.2.2
configobj                 5.0.9
contourpy                 1.3.1
coverage                  7.6.10
cryptography              44.0.0
cycler                    0.12.1
debugpy                   1.8.11
decorator                 5.1.1
decoupler                 1.8.0
defusedxml                0.7.1
dictdiffer                0.9.0
diskcache                 5.6.3
distlib                   0.3.9
distro                    1.9.0
docrep                    0.3.2
dpath                     2.2.0
dulwich                   0.22.7
dvc                       3.58.0
dvc-data                  3.16.7
dvc-http                  2.32.0
dvc-objects               5.1.0
dvc-render                1.0.2
dvc-s3                    3.2.0
dvc-studio-client         0.21.0
dvc-task                  0.40.2
entrypoints               0.4
equinox                   0.11.11
et_xmlfile                2.0.0
etils                     1.11.0
executing                 2.1.0
fastjsonschema            2.21.1
filelock                  3.16.1
flatten-dict              0.4.2
flax                      0.10.2
flufl.lock                8.1.0
fonttools                 4.55.3
formulaic                 1.1.1
formulaic-contrasts       1.0.0
fqdn                      1.5.1
frozenlist                1.5.0
fsspec                    2024.12.0
funcy                     2.0
future                    1.0.0
genomepy                  0.16.1
gitdb                     4.0.12
GitPython                 3.1.44
grandalf                  0.8
grpcio                    1.69.0
gto                       1.7.2
h11                       0.14.0
h5py                      3.12.1
httpcore                  1.0.7
httpx                     0.28.1
huggingface-hub           0.27.1
humanize                  4.11.0
hydra-core                1.3.2
hyperopt                  0.2.7
identify                  2.6.5
idna                      3.10
igraph                    0.11.8
imageio                   2.37.0
importlib_metadata        8.5.0
importlib_resources       6.5.2
iniconfig                 2.0.0
interface-meta            1.3.0
ipykernel                 6.29.5
ipython                   8.31.0
ipywidgets                8.1.5
isoduration               20.11.0
iterative-telemetry       0.0.9
jax                       0.4.38
jax-cuda12-pjrt           0.4.38
jax-cuda12-plugin         0.4.38
jaxlib                    0.4.38
jaxopt                    0.8.3
jaxtyping                 0.2.37
jedi                      0.19.2
Jinja2                    3.1.5
jmespath                  1.0.1
joblib                    1.4.2
json5                     0.10.0
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
jupyter                   1.1.1
jupyter_client            8.6.3
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.11.0
jupyter-lsp               2.2.5
jupyter_server            2.15.0
jupyter_server_terminals  0.5.3
jupyterlab                4.3.4
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
jupyterlab_widgets        3.0.13
kiwisolver                1.4.8
kombu                     5.4.2
lamin_utils               0.13.10
lazy_loader               0.4
legacy-api-wrap           1.4.1
leidenalg                 0.10.2
lightning                 2.5.0.post0
lightning-utilities       0.11.9
lineax                    0.0.7
llvmlite                  0.43.0
loguru                    0.7.3
Markdown                  3.7
markdown-it-py            3.0.0
MarkupSafe                3.0.2
matplotlib                3.10.0
matplotlib-inline         0.1.7
mdurl                     0.1.2
mistune                   3.1.0
ml_collections            1.0.0
ml_dtypes                 0.5.1
mpmath                    1.3.0
msgpack                   1.1.0
mudata                    0.3.1
multidict                 6.1.0
multipledispatch          1.0.0
muon                      0.1.7
mygene                    3.2.2
mysql-connector-python    9.1.0
natsort                   8.4.0
nbclient                  0.10.2
nbconvert                 7.16.5
nbformat                  5.10.4
nest-asyncio              1.6.0
networkx                  3.4.2
nodeenv                   1.9.1
norns                     0.1.6
nose                      1.3.7
notebook                  7.3.2
notebook_shim             0.2.4
numba                     0.60.0
numpy                     1.26.4
numpyro                   0.16.1
nvidia-cublas-cu12        12.4.5.8
nvidia-cuda-cupti-cu12    12.4.127
nvidia-cuda-nvcc-cu12     12.6.85
nvidia-cuda-nvrtc-cu12    12.4.127
nvidia-cuda-runtime-cu12  12.4.127
nvidia-cudnn-cu12         9.1.0.70
nvidia-cufft-cu12         11.2.1.3
nvidia-curand-cu12        10.3.5.147
nvidia-cusolver-cu12      11.6.1.9
nvidia-cusparse-cu12      12.3.1.170
nvidia-nccl-cu12          2.21.5
nvidia-nvjitlink-cu12     12.4.127
nvidia-nvtx-cu12          12.4.127
omegaconf                 2.3.0
openpyxl                  3.1.5
opt_einsum                3.4.0
optax                     0.2.4
orbax-checkpoint          0.11.0
orjson                    3.10.13
ott-jax                   0.5.0
overrides                 7.7.0
packaging                 24.2
pandas                    2.2.3
pandocfilters             1.5.1
papermill                 2.6.0
parso                     0.8.4
pathspec                  0.12.1
patsy                     1.0.1
pertpy                    0.9.5
pexpect                   4.9.0
pillow                    11.1.0
pip                       24.3.1
platformdirs              4.3.6
plottable                 0.1.5
pluggy                    1.5.0
ply                       3.11
pooch                     1.8.2
pre_commit                4.0.1
prometheus_client         0.21.1
prompt_toolkit            3.0.48
propcache                 0.2.1
protobuf                  5.29.2
psutil                    6.1.1
ptyprocess                0.7.0
PubChemPy                 1.0.4
pure_eval                 0.2.3
py4j                      0.10.9.8
pyarrow                   18.1.0
pycparser                 2.22
pydantic                  2.10.4
pydantic_core             2.27.2
pydeseq2                  0.5.0
pydot                     3.0.4
pyfaidx                   0.8.1.3
pygit2                    1.16.0
Pygments                  2.19.1
pygtrie                   2.5.0
pynndescent               0.5.13
Pyomo                     6.8.2
pyparsing                 3.2.1
pyro-api                  0.1.2
pyro-ppl                  1.9.1
pytest                    8.3.4
pytest-pretty             1.2.0
python-dateutil           2.9.0.post0
python-json-logger        3.2.1
pytorch-lightning         2.5.0.post0
pytz                      2024.2
PyYAML                    6.0.2
pyzmq                     26.2.0
ray                       2.40.0
referencing               0.35.1
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.9.4
rpds-py                   0.22.3
rpy2                      3.5.17
ruamel.yaml               0.18.10
ruamel.yaml.clib          0.2.12
s3fs                      2024.12.0
s3transfer                0.10.4
scanpy                    1.10.4
scib-metrics              0.5.1
scikit-image              0.25.1
scikit-learn              1.6.0
scikit-misc               0.5.1
scipy                     1.15.0
scmrepo                   3.3.9
scvi-tools                1.2.2.post2
seaborn                   0.13.2
semver                    3.0.2
Send2Trash                1.8.3
session_info              1.0.0
setuptools                75.7.0
shellingham               1.5.4
shortuuid                 1.0.13
shtab                     1.7.1
simplejson                3.19.3
six                       1.17.0
smmap                     5.0.2
sniffio                   1.3.1
soupsieve                 2.6
sparse                    0.15.4
sparsecca                 0.3.1
sqltrie                   0.11.1
stack-data                0.6.3
statsmodels               0.14.4
stdlib-list               0.11.0
sympy                     1.13.1
tabulate                  0.9.0
tenacity                  9.0.0
tensorboard               2.18.0
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
tensorstore               0.1.71
terminado                 0.18.1
texttable                 1.7.0
threadpoolctl             3.5.0
tifffile                  2025.1.10
tinycss2                  1.4.0
tomlkit                   0.13.2
toolz                     1.0.0
torch                     2.5.1
torchaudio                2.5.1
torchmetrics              1.6.1
torchvision               0.20.1
tornado                   6.4.2
tqdm                      4.67.1
traitlets                 5.14.3
triton                    3.1.0
typer                     0.15.1
types-python-dateutil     2.9.0.20241206
typing_extensions         4.12.2
tzdata                    2024.2
tzlocal                   5.2
umap-learn                0.5.7
uri-template              1.3.0
urllib3                   2.3.0
uv                        0.5.15
vine                      5.1.0
virtualenv                20.28.1
voluptuous                0.15.2
wadler_lindig             0.1.3
wcwidth                   0.2.13
webcolors                 24.11.1
webencodings              0.5.1
websocket-client          1.8.0
Werkzeug                  3.1.3
widgetsnbextension        4.0.13
wrapt                     1.17.0
xarray                    2025.1.0
yarl                      1.18.3
zc.lockfile               3.0.post1
zipp                      3.21.0
Note: you may need to restart the kernel to use updated packages.