# 03 mQTL matrix

This notebook combines information from each donor to a single methylation matrix

In [1]:
import pandas as pd
import pyranges as pr
import os
import datetime

In [2]:
names = [x for x in os.listdir('./donor_binned_data/') if x.endswith('.bed.gz')]

In [3]:
names.sort()
names = [x.replace('B.bed.gz', '') for x in names]
print(names)

['ASA_001', 'ASA_002', 'ASA_004', 'ASA_005', 'ASA_011', 'ASA_015', 'ASA_016', 'ASA_018', 'ASA_020', 'ASA_021', 'ASA_022', 'ASA_024', 'ASA_025', 'ASA_029', 'ASA_031', 'ASA_032', 'ASA_033', 'ASA_034', 'ASA_035', 'ASA_040', 'ASA_041', 'ASA_042', 'ASA_043', 'ASA_046', 'ASA_048', 'ASA_049', 'ASA_050', 'ASA_056', 'ASA_057', 'ASA_058', 'ASA_059', 'ASA_060', 'ASA_064', 'ASA_066', 'ASA_070', 'ASA_079', 'ASA_080', 'ASA_081', 'ASA_082', 'ASA_083', 'ASA_084', 'ASA_085', 'ASA_088', 'ASA_091', 'ASA_092', 'ASA_093', 'ASA_094', 'ASA_095', 'ASA_105', 'ASA_107', 'ASA_108', 'ASA_109', 'ASA_111', 'ASA_112', 'ASA_113', 'ASA_114', 'ASA_115', 'ASA_116', 'ASA_117', 'ASA_118', 'ASA_119', 'ASA_120', 'ASA_121', 'ASA_122', 'ASA_123', 'ASA_124', 'ASA_125', 'ASA_126', 'ASA_127', 'ASA_128', 'ASA_129', 'ASA_130', 'ASA_131', 'ASA_132', 'ASA_133', 'ASA_134', 'ASA_135', 'ASA_136', 'ASA_138', 'ASA_139', 'ASA_140', 'ASA_141', 'ASA_142', 'ASA_143', 'ASA_144', 'ASA_145', 'ASA_148', 'ASA_149', 'ASA_150', 'ASA_153', 'ASA_154', 'ASA_155', 'ASA_158', 'ASA_159', 'ASA_160', 'ASA_161', 'ASA_162', 'ASA_163', 'ASA_164', 'ASA_165', 'ASA_166', 'ASA_167', 'ASA_168', 'ASA_169', 'ASA_170', 'ASA_171', 'ASA_172', 'ASA_173', 'ASA_174', 'ASA_175', 'ASA_176', 'ASA_177', 'ASA_178', 'ASA_179', 'ASA_180', 'ASA_181', 'ASA_182', 'ASA_183', 'ASA_184', 'ASA_185', 'ASA_186', 'ASA_187', 'ASA_188', 'ASA_189', 'ASA_190']

In [4]:
len(names)

125

In [5]:
dfs = {}
for name in names:
    print(name)
    df = pd.read_csv('./donor_binned_data/'+name+'B.bed.gz' )
   # dfs.append(df)
    dfs[name] = df
    print("\n")

ASA_001


ASA_002


ASA_004


ASA_005


ASA_011


ASA_015


ASA_016


ASA_018


ASA_020


ASA_021


ASA_022


ASA_024


ASA_025


ASA_029


ASA_031


ASA_032


ASA_033


ASA_034


ASA_035


ASA_040


ASA_041


ASA_042


ASA_043


ASA_046


ASA_048


ASA_049


ASA_050


ASA_056


ASA_057


ASA_058


ASA_059


ASA_060


ASA_064


ASA_066


ASA_070


ASA_079


ASA_080


ASA_081


ASA_082


ASA_083


ASA_084


ASA_085


ASA_088


ASA_091


ASA_092


ASA_093


ASA_094


ASA_095


ASA_105


ASA_107


ASA_108


ASA_109


ASA_111


ASA_112


ASA_113


ASA_114


ASA_115


ASA_116


ASA_117


ASA_118


ASA_119


ASA_120


ASA_121


ASA_122


ASA_123


ASA_124


ASA_125


ASA_126


ASA_127


ASA_128


ASA_129


ASA_130


ASA_131


ASA_132


ASA_133


ASA_134


ASA_135


ASA_136


ASA_138


ASA_139


ASA_140


ASA_141


ASA_142


ASA_143


ASA_144


ASA_145


ASA_148


ASA_149


ASA_150


ASA_153


ASA_154


ASA_155


ASA_158


ASA_159


ASA_160


ASA_161


ASA_162


ASA_163


ASA_164


ASA_165


ASA_166


ASA_167


ASA_168


ASA_169


ASA_170


ASA_171


ASA_172


ASA_173


ASA_174


ASA_175


ASA_176


ASA_177


ASA_178


ASA_179


ASA_180


ASA_181


ASA_182


ASA_183


ASA_184


ASA_185


ASA_186


ASA_187


ASA_188


ASA_189


ASA_190

In [7]:
# combine all the dataframes into a single dataframe where rows are different 

result = []

result = pd.concat(
    (df.set_index('region_id')['Fraction_modified'].rename(name) for name, df in dfs.items()),
    axis=1
)

In [8]:
result

,ASA_001,ASA_002,ASA_004,ASA_005,ASA_011,ASA_015,ASA_016,ASA_018,ASA_020,ASA_021,...,ASA_181,ASA_182,ASA_183,ASA_184,ASA_185,ASA_186,ASA_187,ASA_188,ASA_189,ASA_190
region_id,,,,,,,,,,,,,,,,,,,,,
chr1:204324_204824,46.604444,80.002222,54.465000,50.383333,45.085000,55.046111,65.138333,43.632778,55.034444,46.374444,...,45.219444,46.654444,50.315000,52.441667,51.041111,49.725556,54.508333,53.495556,47.003889,59.772778
chr1:205018_205518,0.919762,3.746190,0.000000,0.186905,0.132381,0.207857,0.542857,0.295238,0.370714,0.320952,...,0.226667,0.102381,0.103571,0.000000,0.000000,0.099286,0.060952,0.176190,0.325714,0.140000
chr1:206162_206662,27.601667,72.340556,31.851667,31.216111,25.826667,37.820000,49.313889,23.206111,38.438889,22.960000,...,23.773889,31.625556,25.207222,26.920000,28.942778,27.773333,32.850000,35.736667,28.781667,40.457778
chr1:209476_209976,66.152000,98.462000,81.062000,64.472000,60.710000,69.032000,79.722000,63.500000,71.198000,60.304000,...,39.600000,50.558000,70.490000,58.736000,64.114000,58.852000,71.758000,56.702000,50.980000,69.136000
chr1:241571_242071,59.405000,81.991250,64.721250,56.292500,33.321250,55.331250,60.792500,41.412500,58.001250,53.363750,...,44.147500,40.688750,53.985000,53.412500,48.726250,39.737500,52.695000,49.181250,45.732500,46.731250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chr15:73693345_73693845,NaN,NaN,NaN,NaN,NaN,NaN,55.030000,58.726000,61.714000,36.610000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr13:73317295_73317795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.608000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr15:93276182_93276682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.247692,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chr15:69412349_69412849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,72.035714,NaN,73.447857,NaN,NaN,NaN,NaN,NaN,NaN
chr3:54049165_54049665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
result = result.reset_index()

In [10]:
result.shape

(831777, 126)

In [11]:
# remove rows with more than 5 NAs
# result = result.dropna(thresh=len(result.columns) - 5)
# remove rows with any NA
result = result.dropna()

In [12]:
result.shape

(799370, 126)

In [13]:
# get chr start and end from region id
result['Chromosome'] = result['region_id'].str.split(":").str[0]
result['Start'] = result['region_id'].str.extract(r':(\d+)_')[0]
result['End'] = result['region_id'].str.split("_").str[1]

In [14]:
# reorder dataframe
cols = result.columns.tolist()  
new_order = cols[-3:] + cols[:-3]  # Rearrange: last 3 columns + the rest
result = result[new_order]

In [15]:
result

,Chromosome,Start,End,region_id,ASA_001,ASA_002,ASA_004,ASA_005,ASA_011,ASA_015,...,ASA_181,ASA_182,ASA_183,ASA_184,ASA_185,ASA_186,ASA_187,ASA_188,ASA_189,ASA_190
0,chr1,204324,204824,chr1:204324_204824,46.604444,80.002222,54.465000,50.383333,45.085000,55.046111,...,45.219444,46.654444,50.315000,52.441667,51.041111,49.725556,54.508333,53.495556,47.003889,59.772778
1,chr1,205018,205518,chr1:205018_205518,0.919762,3.746190,0.000000,0.186905,0.132381,0.207857,...,0.226667,0.102381,0.103571,0.000000,0.000000,0.099286,0.060952,0.176190,0.325714,0.140000
2,chr1,206162,206662,chr1:206162_206662,27.601667,72.340556,31.851667,31.216111,25.826667,37.820000,...,23.773889,31.625556,25.207222,26.920000,28.942778,27.773333,32.850000,35.736667,28.781667,40.457778
3,chr1,209476,209976,chr1:209476_209976,66.152000,98.462000,81.062000,64.472000,60.710000,69.032000,...,39.600000,50.558000,70.490000,58.736000,64.114000,58.852000,71.758000,56.702000,50.980000,69.136000
4,chr1,241571,242071,chr1:241571_242071,59.405000,81.991250,64.721250,56.292500,33.321250,55.331250,...,44.147500,40.688750,53.985000,53.412500,48.726250,39.737500,52.695000,49.181250,45.732500,46.731250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831224,chrX,154124431,154124931,chrX:154124431_154124931,46.588000,58.806000,38.084000,40.942000,40.666000,46.910000,...,39.800000,43.964000,46.912000,36.852000,44.192000,56.778000,43.030000,36.972000,55.338000,49.362000
831225,chrX,154170631,154171131,chrX:154170631_154171131,79.090000,89.392000,66.004000,62.066000,66.924000,67.194000,...,72.190000,51.896000,61.380000,63.696000,58.422000,54.780000,67.098000,65.692000,48.088000,59.866000
831226,chrX,154184041,154184541,chrX:154184041_154184541,61.414167,85.102500,61.218333,66.746667,53.928333,59.777500,...,55.838333,60.485833,79.203333,72.292500,62.605000,64.094167,57.123333,67.782500,69.673333,65.903333
831227,chrX,154185784,154186284,chrX:154185784_154186284,57.578571,70.492857,54.420000,66.414286,48.208571,60.462857,...,49.047143,59.945714,70.292857,69.070000,55.107143,65.797143,53.997143,58.421429,56.432857,56.980000
831228,chrX,154194788,154195288,chrX:154194788_154195288,29.228889,49.037778,30.091111,26.627778,34.323333,19.032222,...,29.295556,25.446667,32.943750,26.828889,34.983333,33.720000,23.454444,29.272222,32.817500,28.077778

In [16]:
# sort results
result_r = pr.PyRanges(result)
result_r = result_r.sort()
result_final = result_r.df
result_final

,Chromosome,Start,End,region_id,ASA_001,ASA_002,ASA_004,ASA_005,ASA_011,ASA_015,...,ASA_181,ASA_182,ASA_183,ASA_184,ASA_185,ASA_186,ASA_187,ASA_188,ASA_189,ASA_190
0,chr1,204324,204824,chr1:204324_204824,46.604444,80.002222,54.465000,50.383333,45.085000,55.046111,...,45.219444,46.654444,50.315000,52.441667,51.041111,49.725556,54.508333,53.495556,47.003889,59.772778
1,chr1,205018,205518,chr1:205018_205518,0.919762,3.746190,0.000000,0.186905,0.132381,0.207857,...,0.226667,0.102381,0.103571,0.000000,0.000000,0.099286,0.060952,0.176190,0.325714,0.140000
2,chr1,206162,206662,chr1:206162_206662,27.601667,72.340556,31.851667,31.216111,25.826667,37.820000,...,23.773889,31.625556,25.207222,26.920000,28.942778,27.773333,32.850000,35.736667,28.781667,40.457778
3,chr1,209476,209976,chr1:209476_209976,66.152000,98.462000,81.062000,64.472000,60.710000,69.032000,...,39.600000,50.558000,70.490000,58.736000,64.114000,58.852000,71.758000,56.702000,50.980000,69.136000
4,chr1,241571,242071,chr1:241571_242071,59.405000,81.991250,64.721250,56.292500,33.321250,55.331250,...,44.147500,40.688750,53.985000,53.412500,48.726250,39.737500,52.695000,49.181250,45.732500,46.731250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799365,chrX,154124431,154124931,chrX:154124431_154124931,46.588000,58.806000,38.084000,40.942000,40.666000,46.910000,...,39.800000,43.964000,46.912000,36.852000,44.192000,56.778000,43.030000,36.972000,55.338000,49.362000
799366,chrX,154170631,154171131,chrX:154170631_154171131,79.090000,89.392000,66.004000,62.066000,66.924000,67.194000,...,72.190000,51.896000,61.380000,63.696000,58.422000,54.780000,67.098000,65.692000,48.088000,59.866000
799367,chrX,154184041,154184541,chrX:154184041_154184541,61.414167,85.102500,61.218333,66.746667,53.928333,59.777500,...,55.838333,60.485833,79.203333,72.292500,62.605000,64.094167,57.123333,67.782500,69.673333,65.903333
799368,chrX,154185784,154186284,chrX:154185784_154186284,57.578571,70.492857,54.420000,66.414286,48.208571,60.462857,...,49.047143,59.945714,70.292857,69.070000,55.107143,65.797143,53.997143,58.421429,56.432857,56.980000
799369,chrX,154194788,154195288,chrX:154194788_154195288,29.228889,49.037778,30.091111,26.627778,34.323333,19.032222,...,29.295556,25.446667,32.943750,26.828889,34.983333,33.720000,23.454444,29.272222,32.817500,28.077778

In [17]:
result_final = result_final.rename({"Chromosome":"#chr", "Start":"start","End":"end"}, axis =1)

In [18]:
result_final

,#chr,start,end,region_id,ASA_001,ASA_002,ASA_004,ASA_005,ASA_011,ASA_015,...,ASA_181,ASA_182,ASA_183,ASA_184,ASA_185,ASA_186,ASA_187,ASA_188,ASA_189,ASA_190
0,chr1,204324,204824,chr1:204324_204824,46.604444,80.002222,54.465000,50.383333,45.085000,55.046111,...,45.219444,46.654444,50.315000,52.441667,51.041111,49.725556,54.508333,53.495556,47.003889,59.772778
1,chr1,205018,205518,chr1:205018_205518,0.919762,3.746190,0.000000,0.186905,0.132381,0.207857,...,0.226667,0.102381,0.103571,0.000000,0.000000,0.099286,0.060952,0.176190,0.325714,0.140000
2,chr1,206162,206662,chr1:206162_206662,27.601667,72.340556,31.851667,31.216111,25.826667,37.820000,...,23.773889,31.625556,25.207222,26.920000,28.942778,27.773333,32.850000,35.736667,28.781667,40.457778
3,chr1,209476,209976,chr1:209476_209976,66.152000,98.462000,81.062000,64.472000,60.710000,69.032000,...,39.600000,50.558000,70.490000,58.736000,64.114000,58.852000,71.758000,56.702000,50.980000,69.136000
4,chr1,241571,242071,chr1:241571_242071,59.405000,81.991250,64.721250,56.292500,33.321250,55.331250,...,44.147500,40.688750,53.985000,53.412500,48.726250,39.737500,52.695000,49.181250,45.732500,46.731250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799365,chrX,154124431,154124931,chrX:154124431_154124931,46.588000,58.806000,38.084000,40.942000,40.666000,46.910000,...,39.800000,43.964000,46.912000,36.852000,44.192000,56.778000,43.030000,36.972000,55.338000,49.362000
799366,chrX,154170631,154171131,chrX:154170631_154171131,79.090000,89.392000,66.004000,62.066000,66.924000,67.194000,...,72.190000,51.896000,61.380000,63.696000,58.422000,54.780000,67.098000,65.692000,48.088000,59.866000
799367,chrX,154184041,154184541,chrX:154184041_154184541,61.414167,85.102500,61.218333,66.746667,53.928333,59.777500,...,55.838333,60.485833,79.203333,72.292500,62.605000,64.094167,57.123333,67.782500,69.673333,65.903333
799368,chrX,154185784,154186284,chrX:154185784_154186284,57.578571,70.492857,54.420000,66.414286,48.208571,60.462857,...,49.047143,59.945714,70.292857,69.070000,55.107143,65.797143,53.997143,58.421429,56.432857,56.980000
799369,chrX,154194788,154195288,chrX:154194788_154195288,29.228889,49.037778,30.091111,26.627778,34.323333,19.032222,...,29.295556,25.446667,32.943750,26.828889,34.983333,33.720000,23.454444,29.272222,32.817500,28.077778

In [19]:
os.chdir(os.getcwd())
out_dir = "tensor_input_files"
os.makedirs(out_dir, exist_ok = True)

In [20]:
date = datetime.datetime.now().strftime('%Y%m%d')
result_final.to_csv(f'{out_dir}/{date}_mQTL_atac_v1_phenotypes.noindex.bed.gz',sep="\t", index = False)

In [21]:
pip list

Package                              Version
------------------------------------ -----------------
adjustText                           1.0.4
aiohttp                              3.9.3
aiosignal                            1.3.1
anndata                              0.10.5.post1
annoy                                1.17.3
appdirs                              1.4.4
arboreto                             0.1.6
argparse-dataclass                   2.0.0
array_api_compat                     1.5.1
asttokens                            2.4.1
attr                                 0.3.2
attrs                                23.2.0
bbknn                                1.6.0
beautifulsoup4                       4.12.3
bidict                               0.23.1
bioservices                          1.11.2
blosc2                               2.5.1
bokeh                                3.4.0
boltons                              23.1.1
bs4                                  0.0.2
cattrs                               23.2.3
certifi                              2024.2.2
charset-normalizer                   3.3.2
click                                8.1.7
cloudpickle                          3.0.0
colorama                             0.4.6
colorlog                             6.8.2
comm                                 0.2.2
conda-inject                         1.3.1
ConfigArgParse                       1.7
connection_pool                      0.0.3
contourpy                            1.2.0
ctxcore                              0.2.0
cycler                               0.12.1
Cython                               0.29.37
cytoolz                              0.12.3
dask                                 2024.2.1
dataclasses-json                     0.6.4
datrie                               0.8.2
debugpy                              1.8.1
decorator                            5.1.1
dill                                 0.3.8
distributed                          2024.2.1
docutils                             0.20.1
dpath                                2.1.6
easydev                              0.13.1
et-xmlfile                           1.1.0
executing                            2.0.1
fastjsonschema                       2.19.1
fbpca                                1.0
filelock                             3.13.1
fonttools                            4.50.0
frozendict                           2.4.0
frozenlist                           1.4.1
fsspec                               2024.3.1
future                               1.0.0
gensim                               4.3.2
geosketch                            1.2
gevent                               24.2.1
gitdb                                4.0.11
GitPython                            3.1.42
globre                               0.1.5
greenlet                             3.0.3
grequests                            0.7.0
gseapy                               0.10.8
h5py                                 3.10.0
harmonypy                            0.0.9
humanfriendly                        10.0
idna                                 3.6
igraph                               0.11.4
imageio                              2.34.0
immutables                           0.20
importlib-metadata                   7.0.1
importlib_resources                  6.1.2
interlap                             0.2.7
intervaltree                         3.1.0
ipykernel                            6.29.3
ipython                              8.22.2
jedi                                 0.19.1
Jinja2                               3.1.3
joblib                               1.3.2
jsonpickle                           3.0.3
jsonschema                           4.21.1
jsonschema-specifications            2023.12.1
jupyter_client                       8.6.1
jupyter_core                         5.7.2
kaleido                              0.2.1
kiwisolver                           1.4.5
lazy_loader                          0.3
lda                                  3.0.0
leidenalg                            0.10.2
line-profiler                        4.1.2
llvmlite                             0.42.0
locket                               1.0.0
loompy                               3.0.7
loomxpy                              0.4.2
lxml                                 5.1.0
lz4                                  4.3.3
MACS2                                2.2.9.1
markdown-it-py                       3.0.0
MarkupSafe                           2.1.5
marshmallow                          3.21.1
matplotlib                           3.6.3
matplotlib-inline                    0.1.6
mdurl                                0.1.2
mizani                               0.9.3
msgpack                              1.0.8
mudata                               0.2.3
multidict                            6.0.5
multiprocessing_on_dill              3.5.0a4
mypy-extensions                      1.0.0
natsort                              8.4.0
nbformat                             5.10.3
ncls                                 0.0.68
ndindex                              1.8
nest-asyncio                         1.6.0
networkx                             3.2.1
numba                                0.59.0
numexpr                              2.9.0
numpy                                1.26.4
numpy-groupies                       0.10.2
openpyxl                             3.1.2
packaging                            24.0
pandas                               1.5.0
parso                                0.8.3
partd                                1.4.1
patsy                                0.5.6
pexpect                              4.9.0
pillow                               10.2.0
pip                                  24.0
plac                                 1.4.3
platformdirs                         4.2.0
plotly                               5.19.0
plotnine                             0.12.4
polars                               0.20.13
progressbar2                         4.4.2
prompt-toolkit                       3.0.43
protobuf                             5.26.0
psutil                               5.9.8
ptyprocess                           0.7.0
PuLP                                 2.8.0
pure-eval                            0.2.2
py-cpuinfo                           9.0.0
pyarrow                              15.0.0
pyarrow-hotfix                       0.6
pybedtools                           0.9.1
pybigtools                           0.1.2
pyBigWig                             0.3.22
pybiomart                            0.2.0
pycistarget                          1.0a2
pycisTopic                           2.0a0
pyfasta                              0.5.2
pygam                                0.9.0
Pygments                             2.17.2
pynndescent                          0.5.11
pyparsing                            3.1.2
pyranges                             0.0.111
pyrle                                0.0.39
pysam                                0.22.0
pyscenic                             0.12.1+7.g1cd059f
python-dateutil                      2.9.0.post0
python-utils                         3.8.2
pytz                                 2024.1
pyvis                                0.3.2
PyYAML                               6.0.1
pyzmq                                25.1.2
ray                                  2.9.3
referencing                          0.34.0
requests                             2.31.0
requests-cache                       1.2.0
reretry                              0.11.8
rich                                 13.7.1
rich-argparse                        1.4.0
rpds-py                              0.18.0
scanorama                            1.7.4
scanpy                               1.8.2
scatac_fragment_tools                0.1.0
scenicplus                           1.0a1
scikit-image                         0.22.0
scikit-learn                         1.3.2
scipy                                1.12.0
scrublet                             0.2.3
seaborn                              0.13.2
setuptools                           65.5.0
sinfo                                0.3.4
six                                  1.16.0
smart-open                           6.4.0
smmap                                5.0.1
snakemake                            8.5.5
snakemake-interface-common           1.17.1
snakemake-interface-executor-plugins 8.2.0
snakemake-interface-report-plugins   1.0.0
snakemake-interface-storage-plugins  3.1.1
sorted-nearest                       0.0.39
sortedcontainers                     2.4.0
soupsieve                            2.5
stack-data                           0.6.3
statistics                           1.0.3.5
statsmodels                          0.14.1
stdlib-list                          0.10.0
stopit                               1.1.2
suds-community                       1.1.2
tables                               3.9.2
tabulate                             0.9.0
tblib                                3.0.0
tenacity                             8.2.3
texttable                            1.7.0
threadpoolctl                        3.4.0
throttler                            1.2.2
tifffile                             2024.2.12
tmtoolkit                            0.12.0
toolz                                0.12.1
toposort                             1.10
tornado                              6.4
tqdm                                 4.66.2
traitlets                            5.14.2
tspex                                0.6.3
typing                               3.7.4.3
typing_extensions                    4.10.0
typing-inspect                       0.9.0
umap-learn                           0.5.5
url-normalize                        1.4.3
urllib3                              2.2.1
wcwidth                              0.2.13
wheel                                0.43.0
wrapt                                1.16.0
xlrd                                 2.0.1
xmltodict                            0.13.0
xyzservices                          2023.10.1
yarl                                 1.9.4
yte                                  1.5.4
zict                                 3.0.0
zipp                                 3.18.1
zope.event                           5.0
zope.interface                       6.2

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.